use_frameworks!

platform :ios, '13.0'

target 'witte-mobile-library_Example' do
  pod 'witte-mobile-library', :path => '../'

  target 'witte-mobile-library_Tests' do
    inherit! :search_paths

    pod 'Specta', '~> 2.0'
    pod 'Expecta', '~> 1.0' # expecta matchers
  end
end
